### ISSUE TITLE
Question IF rule

### ISSUE THREAD

**Issue by carlos54** [iulica/docx-mailmerge#1]
Hello Iulica, do your fork support de IF{} rule of word for the merging ?

**Comment by carlos54** [comment]
How can pip install your version ?

**Comment by iulica** [comment]
Yes, it works. I contacted Bouke to become the official docx-mailmerge repository, maybe this will happen soon, then I can release it as a new version.

`
pip uninstall docx-mailmerge
pip install git+https://github.com/iulica/docx-mailmerge.git
`
