### ISSUE TITLE
table rows issue

### ISSUE THREAD

**Issue by bloodyburger** [iulica/docx-mailmerge#21]
I have a table defined as below, wondering how to populate data into this?
![image](https://github.com/iulica/docx-mailmerge/assets/7847452/26a601f6-4c4a-4f00-8fb4-3583bc45ce18)

**Comment by iulica** [comment]
you have an example in the Documentation, in the usage.
document.merge_rows("ID", [{"ID": 123, "ProductCode": "abc", ...} , {"ID":124, ... } ])

If you have other fields outside the table that you want replaced, you can also use merge_templates, or merge and give this list of rows as the value of the "ID" attribute. The "ID" attribute can be any attribute inside the table.

Hope this helps

**Comment by iulica** [comment]
Any success here ? @bloodyburger If yes, please close the issue, like and subscribe :)
