### ISSUE TITLE
Barcode: CODE128 not working with whitespaces in string

### ISSUE THREAD

**Issue by polynaught** [iulica/docx-mailmerge#23]
When using docx-mailmerge2 with a word template that has barcodes strings containing whitespaces are being ignored and cause an error inside the replaced mergefield: Required parameters are missing or incorrect.

## Expected Behavior
Whitespaces or other such characters should be accepted as valid string input for calls to { DISPLAYBARCODE { MERGEFIELD param } CODE128 }.

## Current Behavior
As described above, place a barcode inside the docx template and pass it a string containing a whitespace. The barcode will break - however, regular mergefields will accept strings with whitespaces just fine.

## Context
I want to create labels automatically based on csv files that get parsed by python and passed to word docx files through the use of your library docx-mailmerge2.

## Your Environment
Windows
* Python version: 3.12.4
* docx-mailmerge version: docx_mailmerge2-0.8.0-py2.py3-none-any.whl.metadata (6.6 kB)

**Comment by iulica** [comment]
{ DISPLAYBARCODE "{ MERGEFIELD param }" CODE128 }

Any string value that may have spaces should be enclosed in double quotes.
Try it like this, it should work.

**Comment by iulica** [comment]
Did it work ? if yes, please close the issue.

**Comment by iulica** [comment]
closing
