### ISSUE TITLE
merge same field in multiple tables

### ISSUE THREAD

**Issue by tolot27** [iulica/docx-mailmerge#24]
I have several tables in my docx template which have an identifier column in common. If I specify a merge field with the same field name and use `merge_rows`, only the first table is populated with the rows.

How can I apply `merge_rows` to every table which contains the same field name specified in `merge_rows`?

## Your Environment

* Python version: 3.8.10
* docx-mailmerge version: 0.8

**Comment by iulica** [comment]
Hi,

let me see if I understood it correctly. You have several tables that should be filled with the same data, right?

One workaround would be to just use a different identifier and fill the data separately.

I will look into the code to see if there is a problem there.

**Comment by tolot27** [comment]
You got it right. Your proposed workaround requires to duplicate the json data in python with different identifiers several times (=number of tables).

**Comment by iulica** [comment]
Fixed, and released 0.8.1 . Please wait a little bit for the release to be published and then check if it works.
