### ISSUE TITLE
Invalid Syntax Error from v0.8.2

### ISSUE THREAD

**Issue by dwasyl** [iulica/docx-mailmerge#27]
Having just tried the newly released 0.8.2, I'm getting an `Invalid Syntax` error from `mailmerge.py:LN714`:
`    return filename, *match.groups()`

This is running in Python 3.7.

**Comment by iulica** [comment]
I have no more python3.7 and don't seem to be able to install it on my developer machine. I'm testing with 3.8-3.11.

LE: I managed to find another test machine, and got the bugfix release 0.8.3
I will try to add some github workflow actions, such that the test suite is run with all supported versions. Also I will probably drop the python2 support, I'm not even sure it works anymore.

**Comment by dwasyl** [comment]
Amazing @iulica thank you very much for making the fix. I should probably get everything moved up to at least 3.9 mind you. Yes, I think might be time to officially say 2.7 is retired.
