### ISSUE TITLE
Images on Header is ruptured after running document.merge_templates() - 'The picture can't be displayed'

### ISSUE THREAD

**Issue by drquochoai** [iulica/docx-mailmerge#28]
### Problems:
Images on Header is ruptured after running `document.merge_templates()`
![image](https://github.com/user-attachments/assets/374eba3d-23bf-46f4-8bef-177ac8b38794)
### I have tested that the images is ruptured right after running the code :
`        document.merge_templates([giaTriFields], separator="page_break")
`
## Expected Behavior
Should be show as the template docx file:
![image](https://github.com/user-attachments/assets/c9165e24-3bf2-4cc9-9567-68587eca6619)

### Solved :
🚫🚫 Do not use **.merge_templates** : `# document.merge_templates([giaTriFields], separator="page_break")`

✅✅Change to **.merge:** `document.merge(**giaTriFields)`
## Your Environment

* Python version: Python 3.8.19
* docx-mailmerge version: docx-mailmerge2 0.8.3

**Comment by iulica** [comment]
Thanks for the detailed report.

If the header/footer contain an image or something that contains an unique ID, the proper way is to use merge and not merge_templates.

I just noticed you mention the solution yourself.

The right implemenatation that takes care of this is a little bit more difficult. I have already fixed it and will include it in a next release. However, it only works if you have just one row in the replacements, which is equivalent to the merge() function anyways.
