### ISSUE TITLE
IF doesn't apply properly

### ISSUE THREAD

**Issue by carlos54** [iulica/docx-mailmerge#3]
When I try your unittest exemple with this code, the if doesn't apply
```
from mailmerge import MailMerge

doc_data = {}
doc_data["fieldname"] = "tree"
document = MailMerge(
    "/home/user/src/mailing-api/mailing/test/code_snipet/test_nested_if_inside.docx"
)
document.merge_templates([doc_data], separator="textWrapping_break")
document.write(
    "/home/user/src/mailing-api/mailing/test/code_snipet/merge_test/test_out_if.docx"
)
```
## Expected Behavior
Like word do it

## Current Behavior
The If doesn't apply  the result is  -one- instead of "more:tree" (see test_out_if.docx attached)

## Possible Solution
I'm missing something...

## Steps to Reproduce (for bugs)
Run the code with your test_nested_if_inside.docx template.

## Your Environment
* Python version: 3.9.7
* docx-mailmerge version: current master repo 
[test_out_if.docx](https://github.com/iulica/docx-mailmerge/files/8331845/test_out_if.docx)

**Comment by iulica** [comment]
If you check the documentation, you see that there is no way for docx-mailmerge to automatically update outer fields like IF or INCLUDEPICTURE. You have two solutions:
1. Open the docx, select everything (ctrl-a/cmd-a) then press F9 to update the fields. Now Word will update the IF value accordingly.
2. Use the auto-update feature. 
document = MailMerge(
    "/home/user/src/mailing-api/mailing/test/code_snipet/test_nested_if_inside.docx",
   auto_update_fields_on_open="auto"
)

Here is the quote from the docs:

`If the fields are nested inside other fields, the outer fields need to be updated in Word. This can be done by selecting everything (CTRL-a) and then update the fields (F9). There is a way to force the Word to update fields automatically when opening the document. docx-mailmerge can set this setting when saving the document. You can configure this feature by using the auto_update_fields_on_open parameter. The value always will set the setting regardless if needed or not and the value auto will only set it when necessary (when nested fields exist). The default value no will not activate this setting.`

**Comment by iulica** [comment]
Let me know if this works for you so I can close the issue.

**Comment by carlos54** [comment]
I just test now, yes it works thanks.
