### ISSUE TITLE
 Date formatting is work in progress.

### ISSUE THREAD

**Issue by carlos54** [iulica/docx-mailmerge#5]
Do you think that date formatting will be available soon ?

`   { MERGEFIELD my_date \@ "YYYYMMD" }`

**Comment by iulica** [comment]
As soon as I will have some time. The implementation is prepared, the function needs just someone to work on it. I have seen a PR in the original repository, #57. I will contact the person, perhaps he would like to contribute it again.

[https://github.com/Bouke/docx-mailmerge/pull/57](url)

**Comment by iulica** [comment]
I just committed support for date formatting. Can you check if everything is fine ?

**Comment by carlos54** [comment]
Nice, thank you, I will check ASAP. Have a nice day.
