### ISSUE TITLE
Merge_Templates

### ISSUE THREAD

**Issue by omar-haikal** [iulica/docx-mailmerge#6]
# Merge Templates Request

## Issue Description
I am currently trying to merge a document that contains multiple pages. The second page contains a table composed of two rows with different mailmerge fields on each row. I am trying to have this table repeated for my dataframe. 

The issue that arises when using the merge templates method is that the entire document is repeated for every dataframe row. 
I have also attempted to use the merge table function, but because of the anchor input and my table hanging different mailmerge fields in each row, this is not resulting in the correct output.

**Comment by iulica** [comment]
Could you create a simple example that shows your issue?

Are you able to mailmerge the document using Microsoft Word?

**Comment by omar-haikal** [comment]
Thank you for your quick response. Please find a simple example for this issue

## Sample Data 
![image](https://user-images.githubusercontent.com/106988669/174477986-b20a8310-c8b6-42fb-af38-01048c6edc10.png)

** The first paragraph should not be repeated, only the table below should be repeated **

## Result with merge_templates

**Comment by iulica** [comment]
I do not believe this is possible, even with the Microsoft Word Mailmerge. Merge Table functionality would not work as the duplication is done at row level.
What I would suggest is to split the template document into 2 parts. The one fixed that contains the first page, that doesn't need to be repeated, and a second document with the table, that need to be repeated.
Then, you can mail merge them independently (I don't know if the first page has fields or not), and then join them together into the final word document. (you can use python-docx for this)
It's slightly more complicated but you can manage an automated script.

**Comment by omar-haikal** [comment]
@iulica 
Thank you for your response. I have thought about this solution as well, and while it is not completely ideal, I will see to its implementation. 

As a side note, is there any possibility that this can be done with the `merge_rows` method. Based on my understanding, the anchor specifies the first column where the merge field occurs. Would it be possible to input a list of anchors, so that two or more rows of the table are in each iteration of the method. I have tried looking at the source code, but I guess I am not at the level where I can implement this change on my own

**Comment by iulica** [comment]
merge_rows and also merge/merge_templates when you give a list as a value to one field, can be used to expand multiple tables. But they are expanded separately and you will get something like this:
table:
row1 value1
row1 value2
row1 ... value  n
row2 value1
...
row2 value n

I see your updated answer and it's exactly this

**Comment by iulica** [comment]
I will think about a solution like this, maybe to include several rows instead of just one row. Will come back with an answer

**Comment by omar-haikal** [comment]
Thank you so much

**Comment by iulica** [comment]
I got another idea that might work. Can you just make one table with one row and one column, and inside that one row create another table that looks like yours. This might give you the needed result.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/1836344/174491620-f5df7f29-4fa9-4708-b5ed-3f4166daf9fb.png">

**Comment by omar-haikal** [comment]
Genius Solution! It is working as intended 

![image](https://user-images.githubusercontent.com/106988669/174497740-8994f2ec-795b-49e3-97ca-b095d907b581.png)

Thank you so much for assisting on this issue, you have saved me a lot of lines of code
