### ISSUE TITLE
treat docx with merged table cell?

### ISSUE THREAD

**Issue by muhammadfarizarya** [iulica/docx-mailmerge#9]
if I try to fill the mailmerge field in a table, and if the table has merged cell, doc-mailmerge will un-merge the merged cell.
how can we treat such case? Thanks

I repost issue from old repository https://github.com/Bouke/docx-mailmerge/issues/104

**Comment by iulica** [comment]
Can you give a test word document and an example? It will make it easier to implement the feature.
